### ISSUE TITLE
.help utan argument borde göra något Konstruktivt (vad?)

### ISSUE THREAD

**Issue by kqr** [memery/memery-legacy#38]

**Comment by nycz** [comment]
Fixade en simpel beskrivning/placeholder (borde ändras typ asap) i commit e05526f4db

**Comment by kqr** [comment]
Vill helst länka till commands-lista/plugins-lista @ github men det vill jag helst inte stoppa in förrän autodeployment är på platz, eftersom annars riskerar listan att vara utdaterad när den används. :c

Kan stoppa in ändå förstås…

**Comment by kqr** [comment]
Vänta oj. Det var det jag ville ha .list commands/.list plugins till. Justeja. Då borde help bara referera till dem, kanske. Och berätta att .help <command/plugin> ger hjälp om ett kommando/plugin, typ.
