### ISSUE TITLE
.help kan inte rikta sitt svar till någon (kräver massivt fulhakk i interpretor…)

### ISSUE THREAD

**Issue by kqr** [memery/memery-legacy#47]

**Comment by nycz** [comment]
Såg ut som om den kunde det förut, men eh. Nu kan den rikta sitt svar till hela världen iom commit e05526f4db

Venne riktigt om det skulle bli så snyggt tho? Kanske borde komma på nån övergripande policy ang. vad som ska nudgas och vad som inte ska det.

...eller menar du att PRIVMSGa direkt till någon? (det borde väl funka tho)

**Comment by kqr** [comment]
Nä menar i kanalen. Generellt så har min "övergripande policy" (ehe) varit att kommandon som man oftast menar till "andra" (något löst definierat) inte ska nudgea, texempel .lastfm (varför skulle man vilja veta själv vad man lyssnar på?) eller .commit (tänkt som roligt svar när någon ställer en fråga.) Meeeen om vi har en fungerande @nick-feature så är ju det överflödigt och då kan alla kommandon nudgea. Typ.
