### ISSUE TITLE
Bestäm språkstandard för memery

### ISSUE THREAD

**Issue by nycz** [memery/memery-legacy#49]
Svengelska luktar wanna b amerikan :/

Koden och kommentarerna är (vad jag vet) huvudsakligen på engelska, commits och issues är svenska, memery själv växlar vilt mellan svenska och engelska och även mellan ircsnack och stora bokstäver+punkt.

Errors och exceptions kommer ju att fortsätta vara på engelska, och commands tenderar att vara på svenska, men resten är typ rysk roulette i google translate ;_;

**Comment by kqr** [comment]
Hahahahahaha alltså hm. Bäst är egentligen att anglofilera hela projektet, men jag vill ändå ha svensk memery, så uh -- jag funderar på språkpaket. I själva roten av projektet kan man lätt ha json/andra filer som är [{"sentence": "mening"}] och sen bara slå upp "sentence" i motsvarande språkfil.

Plugins/kommandon är väl problemet. Plugins går det säkert att göra något hippt med, så de har en språkdict i sig som används, men kommandon är värre. Jag vet inte hur man löser dem.
