### ISSUE TITLE
QUIT-meddelandet registreras inte alltid

### ISSUE THREAD

**Issue by nycz** [memery/memery-legacy#51]
Ibland/ofta står det bara Client Quit som quitmsg D: 
Kan vara för att hon stänger connectionen för fort.

**Comment by slaeshjag** [comment]
Mh, har observerat det med fanbot3. Går inte att göra något åt det afaik, det är IRC-servern som ignorerar. Client Quit betyder att QUIT-kommandor registrerades iaf.
