### ISSUE TITLE
översätt allt som går till Ordentlig Svenska (nåja)

### ISSUE THREAD

**Issue by kqr** [memery/memery-legacy#55]

**Comment by nycz** [comment]
Ett bra exempel på hur det INTE ska skrivas >:/

> Hej Och Välkommen Till {}, En Vänlig Och Hjälpsam IRC (InterNet Relay Chat) "Bot"

Tycker hon kan ha kvar lite av sin surhet som sagt, men på svenska och med lite bättre grammatik.
