### ISSUE TITLE
ficza plugins som läser från internet så de tolkar &quot; n stuff med common.unescape (prerequisites: #56)

### ISSUE THREAD

**Issue by kqr** [memery/memery-legacy#58]

**Comment by nycz** [comment]
När du är mindre sömnig och inte äter eller förlorar/vinner i schack, vad är kvar på det här issuet?

**Comment by kqr** [comment]
`c.py` är kvar, men borde vara den enda. Det finns ett gäng regexes som omvandlar hex-escapes till riktiga tecken i den; det är _inte_ på formen `&#39;` utan mer `\\x39` typ. Jag trodde att det var html-escapes men det är det inte. Jag är inte bra på att jobba med text så jag vet inte hur man bör hantera sånt där. Jag tycker att det borde finnas något inbyggt. o_O

**Comment by nycz** [comment]
Hittade problemet! Texten var kodad som unicode men inte med unicodetecken utan tecken för tecken... typ o_O unicode i unicode iaf, och det löses med codecs-modulen och unicode_escape-encodingen. Sen var det bara att htmlunescapa resten av skiten.

Atm har jag inte lagt in nåt i common, säg till om du tycker det behövs.
