### ISSUE TITLE
Wolfram Alpha plugin

### ISSUE THREAD

**Issue by nycz** [memery/memery-legacy#61]
Tror det kunde vara ett bra komplement till .g, .ud och .wik (som ju dessutom är fulhakk fortf >:o )

Finns ett api men det har en begränsning på 2000 queries per månad (knappt 70 om dagen)... men det kanske räcker iofs. Skulle behöva spamma .wa ganska mycket annars o_O

iaf, tror inte det är ett (bra/möjligt) alternativ att regexa ut skiten direkt, så eh.

**Comment by kqr** [comment]
Jag har funderat på Wolfram Alpha länge men trodde att API:t var kommersiellt och kostade pengar. Regexa blir svårt när sidan verkar drivas med js. x)

70/dag låter lite, men 2000 per månad är ganska mycket ändå. Queries lär komma i spurter på max 50/gång, och så många såna gånger per månad är det inte, så I say go for it!

**Comment by kqr** [comment]
(bumpar upp prioritet till normal)

**Comment by jocke-l** [comment]
finns det ingen python js-parser då?

**Comment by kqr** [comment]
Ska vara mer än en parser. Krävs en hel js-motor inklusive DOM och skit. Myyycket skräp för att lösa det på fulhakkssätt när det finns ett finfint API.

**Comment by kqr** [comment]
This is done!
