### ISSUE TITLE
Användningsstatistik

### ISSUE THREAD

**Issue by kqr** [memery/memery-legacy#62]
I och med Wolfram Alpha-begränsningen på 2000 queries/månad tänkte jag att det kunde vara intressant om memery förde statistik över sin användning: reloads, help, plugins, title etc. Tufft men inget nödvändigt. (Går ju att uppskatta med loggar anyway om man verkligen behöver det.)

**Comment by nycz** [comment]
Hm yas det vore ju lite tufft. Är det enklast att göra med JSON eller SQL eller nåt annat tho?

**Comment by kqr** [comment]
Stängs i och med https://github.com/kqr/memery/issues?milestone=4
