### ISSUE TITLE
.markov - random markov chains som plugin

### ISSUE THREAD

**Issue by nycz** [memery/memery-legacy#64]
Troligtvis med loggar från kanalen som referens

Kräver #19 om det ska vara något intressant.

**Comment by kqr** [comment]
Kräver dessutom att plugins får veta vilken kanal de är i etc. o_O

Det kanske är lättast att inte implementera som plugin från början.

**Comment by kqr** [comment]
Jag föreslår wontfix på denna pga inkompatibelt med nuvarande pluginsystem. Man skulle väl kunna stoppa in en .markov i interpretor.py som tar som argument ord man seedar den med, men jag vet inte hur mycket det kladdar ned interpretor vs hur mycket nytta det gör.
