### ISSUE TITLE
restart borde göra reload automagiskt

### ISSUE THREAD

**Issue by kqr** [memery/memery-legacy#74]

**Comment by nycz** [comment]
FTR behöver den inte uppdatera config, det sker automagiskt när irc.py körs.

**Comment by nycz** [comment]
Hm, frågan är vad som ska hända om reload failar för en eller flera moduler. Ska memery restarta i alla fall? Eller ska det typ krävas restart --force om reloaden failar?

**Comment by kqr** [comment]
Det senare låter klokast.
