### ISSUE TITLE
Kommando som ger admins möjlighet att skicka råa irc-meddelanden?

### ISSUE THREAD

**Issue by kqr** [memery/memery-legacy#78]
Det skulle vara väldigt lätt att implementera (tror jag o_O) och framförallt ger det möjlighet att göra funky saker som inte går att göra på andra sätt; som fallback. Å andra sidan vet jag inget som skulle behöva det just nu. Vad säger andra?

**Comment by nycz** [comment]
```
memery: rawsend [ircmsg]
```

Löjligt enkelt (bara regexa in ircmsg till send()) men potentiellt vääääääldigt osäkert o_O men eh, så länge det är admincommand, i spose...

Och nope, vet inget som behöver det nu heller.

**Comment by nycz** [comment]
Frågan är väl om det här kommandot är viktigt nog att bloata ner irc.py med? Annars borde det bli wontfix.

**Comment by kqr** [comment]
Nopenope. Inte tills vidare i alla fall. Kan öppna på nytt om det behövs.
